# Generated by Django 2.1.2 on 2018-10-27 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CursoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UniversidadeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_universidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='departamentomodel',
            name='id_universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UniversidadeModel'),
        ),
        migrations.AddField(
            model_name='cursomodel',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DepartamentoModel'),
        ),
        migrations.AddField(
            model_name='alunomodel',
            name='id_universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UniversidadeModel'),
        ),
    ]
