# Generated by Django 2.1.2 on 2018-10-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=25, verbose_name='Nome do Aluno')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Aluno',
                'ordering': ['nome_aluno'],
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='CursoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Curso',
                'ordering': ['nome_curso'],
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_departamento', models.CharField(max_length=100, verbose_name='Nome do Departamento')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Departamento',
                'ordering': ['nome_departamento'],
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'ordering': ['nome_disciplina'],
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='UniversidadeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_universidade', models.CharField(max_length=100, verbose_name='Nome Universidade')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Universidade',
                'ordering': ['nome_universidade'],
                'verbose_name_plural': 'Universidades',
            },
        ),
        migrations.AddField(
            model_name='departamentomodel',
            name='id_universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.UniversidadeModel'),
        ),
        migrations.AddField(
            model_name='cursomodel',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.DepartamentoModel'),
        ),
        migrations.AddField(
            model_name='alunomodel',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CursoModel'),
        ),
        migrations.AddField(
            model_name='alunomodel',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.DepartamentoModel'),
        ),
        migrations.AddField(
            model_name='alunomodel',
            name='id_universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.UniversidadeModel'),
        ),
    ]
