# Generated by Django 2.1.2 on 2018-10-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidademodel',
            name='slug',
            field=models.SlugField(default=1, max_length=100, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
