# Generated by Django 2.1.2 on 2018-10-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_universidademodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universidademodel',
            name='slug',
        ),
    ]
