# Generated by Django 2.1.2 on 2018-10-28 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_universidademodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunomodel',
            name='id_departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.DepartamentoModel'),
            preserve_default=False,
        ),
    ]
