# Generated by Django 2.1.2 on 2018-10-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alunomodel_id_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunomodel',
            name='nome_aluno',
            field=models.CharField(max_length=25, verbose_name='Nome do Aluno'),
        ),
    ]
